### PR TITLE
product ticket done

### PR DESCRIPTION
**Pull request by stjepad**
## Link to Ticket
Closes # [Link](https://github.com/NSS-Enthusiastic-Camels/BangazonAPI/issues/4)

## Description of Proposed Changes
- Created model for Payment
- Created mvc for Payment

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout <dsSetUpl>
Add filler payment data into your SQL
```

Test 

-Get
-Endpoint: 
http://localhost:5000/api/Product

-Get/1
-Endpoint:
http://localhost:5000/api/Product/1

-POST
- Endpoint:
 http://localhost:5000/api/Product

- Example body: 
```
{
    "title": "Bloop",
    "price": 32,
    "description": " meow",
    "quantity": 11,
    "createdAt": "0001-01-01T00:00:00",
    "customerId": 1,
    "productTypeId": 1,
}
```
-PUT
-endpoint:
 http://localhost:5000/api/Product/{id}

- Example body: 
```
{
    "title": "Bloop!!!",
    "price": 32,
    "description": " meow",
    "quantity": 11,
    "createdAt": "0001-01-01T00:00:00",
    "customerId": 1,
    "productTypeId": 1,
}
```
- DELETE
- Endpoint:
http://localhost:5000/api/Product/{id}

## Impacted Areas in Application

List general components of the application that this PR will affect:

* Payment Model and Payment Controller

## Mentions @username

@alexfont321
@priyankagargc27
@MarkHale94 

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

### CODE REVIEW

**Review by MarkHale94 — APPROVED** [review]
Looks good

**Comment by megducharme** [comment]
Great job! 🔥

**Comment by priyankagargc27** [comment]
looks good to me !

**Review by alexfont321 — APPROVED** [review]
looks good!

**Pull request merged**
