### PR TITLE
Departments done

### PR DESCRIPTION
**Pull request by stjepad**
## Link to Ticket
closes # [Link](https://github.com/NSS-Enthusiastic-Camels/BangazonAPI/issues/6)

## Description of Proposed Changes

- Create model for Department
- Created mvc for Department

## Steps to Test
1.
```
git fetch --all
git checkout dsSetUp
```
2.
Fill in a few dummy datas in sql. Example below.
```
insert into Department
 (Name,Budget) VALUES ('Education',30000);
```
```
insert into Employee

(FirstName,LastName,DepartmentId,IsSuperVisor)

VALUES ('Mark','Hale',1,1);
```

3.
Test Get all:
in postman get with URL
```
http://localhost:5000/api/department
```
4.
Test Get single:
in postman get with URL
```
http://localhost:5000/api/department/1
```
5.
Test Post:
in postman post with URL
```
http://localhost:5000/api/department
```
in body paste
```
    {
        "name": "Custodian",
        "budget": 500000
    }
```
Get departments again to see outcome.

6.
Test Put:
in postman put with URL
```
http://localhost:5000/api/department/{id}
```
in body paste
```
    {
        "name": "Janitors",
        "budget": 500000
    }
```
Get departments to see outcome.

7.
Test ?_include=employees:
in postman get with URL
```
http://localhost:5000/api/department/1?_include=employees
```
It should show all employees and their details for department with the id 1.

8.
test ?_filter=budget&_gt=300000:
in postman get with URL
```
http://localhost:5000/api/department?_filter=budget&_gt=300000
```
It should show all budgets greater than 300,000.

## Impacted Areas in Application

List general components of the application that this PR will affect:

* DepartmentModel and DepartmentlController

## Mentions @username

@alexfont321
@priyankagargc27 
@markhale94

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

### CODE REVIEW

**Review by MarkHale94 — CHANGES_REQUESTED** [review]
Please make the filter for budget be greater than or equal to, rather than just greater than. Also please include insert statements for employees so that they will appear in the postman calls.

**Comment by stjepad** [comment]
Done.
Ready for approval

**Review by MarkHale94 — APPROVED** [review]
good stuff

**Review by alexfont321 — APPROVED** [review]
YEA BABAY!!!

**Pull request merged**
